spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1dhk03x3x025izduo.mysql.rds.aliyuncs.com:3306/xb-blog-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: xblog
    password: 123qwe!@#
    name: xb-blog-test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1000000